### ISSUE TITLE
Auto-generate the `slug` value when creating new Services

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Services#21]
Unable to create new services due to:

@type :"ConstraintViolationList"
hydra:description: "slug: This value should not be blank."

**Comment by StephenOTT** [comment]
@bushra was this resolved with: https://github.com/DigitalState/Admin/commit/f4a924c9e39e0089ad4f316742bdc253aac3dee1 ?

**Comment by baddlan** [comment]
Yes, that fixes it on the UI side.
