### ISSUE TITLE
Error occurs when creating new Submissions

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Services#24]
Tested the Postman example with body:
```
{
	"scenario": "/scenarios/{SCENARIO_UUID}",
	"data": { 
		"test": "test" 
	},
	"version": 1
}
```

Error:
```
{
    "type": "https://tools.ietf.org/html/rfc2616#section-10",
    "title": "An error occurred",
    "detail": "",
    "violations": []
}
```

**Comment by mario-digitalstate** [comment]
Forgot to mention, the /submissions endpoint is strictly administrative now.

The public endpoint for submissions is now /scenarios/{uuid}/submissions. You also no longer need to provide the scenario and version attribute, just data.

**Comment by StephenOTT** [comment]
resolved
