### ISSUE TITLE
Unable to delete services or scenarios

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Services#25]

**Comment by mario-digitalstate** [comment]
Doctrine soft-deletable filter is in place.

The real issue is adding a doctrine filter that filters out deleted items on GET

**Comment by StephenOTT** [comment]
@mario-DigitalState, when can we add the doctrine filter?

As a core feature would be good to have a optional filter that allows you to see the soft deleted items.  Something like:
IncludeSoftDeleted = false by default
But doing true means the soft deleted items are shown. 

Maybe also a filter that only shows the soft deleted?

**Comment by mario-digitalstate** [comment]
Theres 2 types of filters here:
-Api search filters, it would be ?deletedAt=null|not-null, for administration
-Doctrine filter with ACL intentions (force deletedAt=null for individuals/anonymous users)

**Comment by mario-digitalstate** [comment]
Added deleted=true|false|null query param filter c14771bce45596aa2921f0db03e6eace748d82d2
